import { type NextPage } from "next";
import Head from "next/head";
import { ItemsList } from "~/components/ItemsList";
import { PageLayout } from "~/components/Layout";

const MenuPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Menu - Restidy T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <ItemsList />
      </PageLayout>
    </>
  );
};

export default MenuPage;
