import { type GetStaticProps, type NextPage } from "next";
import Head from "next/head";
import { PageLayout } from "~/components/Layout";
import { api } from "~/utils/api";
import { LoadingSpinner } from "~/components/Primary/LoadingSpinner";
import { useRouter } from "next/router";
import { SmtWrong } from "~/components/Primary";
import MenuSection from "~/components/Menu/MenuSection";
import SectionsHeader from "~/components/Menu/SectionsHeader";
import MenuNavbar from "~/components/Menu/Navbar";
import { generateSSGHelper } from "~/server/helpers/ssgHelper";
import useFieldTranslation from "~/utils/hooks/useFieldTranslation";

const MenuSectionPage: NextPage<{ menuSlug: string }> = ({ menuSlug }) => {
  const { toLocale } = useFieldTranslation();
  const router = useRouter();
  const sectionSlug = router.query?.section as string;
  const { data: store, isLoading: isLoadingStore } =
    api.stores.getStore.useQuery();
  const { data: storeConfig, isLoading: isLoadingConfig } =
    api.stores.getConfig.useQuery();
  const { data: menu, isLoading } = api.menus.getBySlug.useQuery({
    slug: menuSlug,
  });

  const section = menu?.sections?.find((item) => item.slug === sectionSlug);

  if (isLoading || isLoadingConfig || isLoadingStore) return <LoadingSpinner />;
  if (!section || !menu || !store) return <SmtWrong />;

  return (
    <>
      <Head>
        <title>
          {store.name} - {toLocale(section, "name") ?? ""} (
          {toLocale(menu, "name") ?? ""})
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout bgImgs={storeConfig?.bgImgs?.split(";")}>
        <MenuNavbar />
        <SectionsHeader menu={menu} />
        <MenuSection section={section} />
      </PageLayout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const ssg = generateSSGHelper();

  const menuSlug = context.params?.menu as string;
  const sectionSlug = context.params?.section as string;

  if (typeof menuSlug !== "string") throw new Error("no menu");
  if (typeof sectionSlug !== "string") throw new Error("no section");

  await ssg.menus.getBySlug.prefetch({ slug: menuSlug });
  await ssg.stores.getConfig.prefetch();

  return {
    props: {
      trpcState: ssg.dehydrate(),
      menuSlug,
    },
  };
};

export const getStaticPaths = () => {
  return { paths: [], fallback: "blocking" };
};

export default MenuSectionPage;
