import { type NextPage } from "next";
import Head from "next/head";
import { PageLayout } from "~/components/Layout";
import { api } from "~/utils/api";
import { type Store } from "@prisma/client";
import { LoadingSpinner } from "~/components/Primary/LoadingSpinner";
import { useRouter } from "next/router";
import { SmtWrong } from "~/components/Primary";
import MenuSection from "~/components/Menu/MenuSection";
import SectionsHeader from "~/components/Menu/SectionsHeader";

const MenuSectionPage: NextPage = ({ store }: { store?: Store }) => {
  const router = useRouter();
  const menuSlug = router.query?.menu as string;
  const sectionSlug = router.query?.section as string;

  const { data: menus, isLoading } = api.menus.getAll.useQuery();

  const selectedMenu = menus?.find((menu) => menu.slug === menuSlug);
  const selectedSection = selectedMenu?.sections?.find(
    (item) => item.slug === sectionSlug
  );

  if (isLoading) return <LoadingSpinner />;
  if (!selectedSection || !selectedMenu) return <SmtWrong />;

  return (
    <>
      <Head>
        <title>Menu - {store?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <SectionsHeader menu={selectedMenu} isLoading={isLoading} />
        <MenuSection section={selectedSection} />
      </PageLayout>
    </>
  );
};

export default MenuSectionPage;
