import { type NextPage } from "next";
import Head from "next/head";
import { PageLayout } from "~/components/Layout";
import { api } from "~/utils/api";
import { type Store } from "@prisma/client";
import { LoadingSpinner } from "~/components/Primary/LoadingSpinner";
import SectionsList from "~/components/Menu/SectionsList";
import { SmtWrong } from "~/components/Primary";
import { useRouter } from "next/router";
import MenuNavbar from "~/components/Menu/Navbar";

const MenuPage: NextPage = ({ store }: { store?: Store }) => {
  const router = useRouter();
  const menuSlug = router.query?.menu as string;

  const { data: menus, isLoading } = api.menus.getAll.useQuery();
  const selectedMenu = menus?.find((menu) => menu.slug === menuSlug);

  if (isLoading) return <LoadingSpinner />;
  if (!selectedMenu) return <SmtWrong />;

  return (
    <>
      <Head>
        <title>Menu - {store?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <MenuNavbar />
        <SectionsList menu={selectedMenu} isLoading={isLoading} />
      </PageLayout>
    </>
  );
};

export default MenuPage;
