import { type NextPage } from "next";
import Head from "next/head";
import { PageLayout } from "~/components/Layout";
import { api } from "~/utils/api";
import { LoadingSpinner } from "~/components/Primary/LoadingSpinner";
import SectionsList from "~/components/Menu/SectionsList";
import { SmtWrong } from "~/components/Primary";
import { useRouter } from "next/router";
import MenuNavbar from "~/components/Menu/Navbar";

const MenuPage: NextPage = () => {
  const router = useRouter();
  const ctx = api.useContext();
  const menuSlug = router.query?.menu as string;

  const { data: menus, isLoading } = api.menus.getAll.useQuery({
    active: true,
  });
  const selectedMenu = menus?.find((menu) => menu.slug === menuSlug);

  if (isLoading) return <LoadingSpinner />;
  if (!selectedMenu) return <SmtWrong />;

  return (
    <>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <MenuNavbar />
        <SectionsList menu={selectedMenu} isLoading={isLoading} />
      </PageLayout>
    </>
  );
};

// MenuPage.getInitialProps = ({ req }) => {
//   // // FOR WHEN NEEDED ONLY ON CLIENT SIDE
//   // const code = window.location.host.split(".")[0] as string;
//   // FOR WHEN THEY'RE NEEDED AT SERVER SIDE
//   const code = req?.headers?.host?.split(".")[0] as string;
//   if (typeof code !== "string") throw new Error("No store found");

//   return { code };
// };

export default MenuPage;
