import { Loader } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import { PageLayout } from "~/components/Layout";
import { api } from "~/utils/api";
import { type Store } from "@prisma/client";
import { Centered } from "~/components/Primary/LoadingSpinner";
import MenusList from "~/components/Menu/MenusList";

const MenusPage: NextPage = ({ store }: { store?: Store }) => {
  const { data: menus, isLoading } = api.menus.getAll.useQuery();

  if (isLoading || !menus)
    return (
      <Centered>
        <Loader />
      </Centered>
    );

  return (
    <>
      <Head>
        <title>Menu - {store?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <MenusList menus={menus} isLoading={isLoading} />
      </PageLayout>
    </>
  );
};

export default MenusPage;
